USE market;

DROP TABLE IF EXISTS users_table;

CREATE TABLE users_table
(id INT NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,password TEXT NOT NULL,zipcode VARCHAR(8) NOT NULL,address VARCHAR(100) NOT NULL,telephone VARCHAR(15) NOT NULL,PRIMARY KEY(id));
