USE market;

DROP TABLE IF EXISTS users_table;

CREATE TABLE users_table
(id INT NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,email VARCHAR(100) NOT NULL,password TEXT NOT NULL,zipcode VARCHAR(8) NOT NULL,address VARCHAR(100) NOT NULL,telephone VARCHAR(15) NOT NULL,PRIMARY KEY(id));

DROP TABLE IF EXISTS items_table;
CREATE TABLE items_table
(id INT NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,description TEXT NOT NULL,price INT NOT NULL,image_path TEXT NOT NULL,category TEXT NOT NULL NOT NULL,PRIMARY KEY(id));

DROP TABLE IF EXISTS comments_table;
CREATE TABLE comments_table
(id INT NOT NULL AUTO_INCREMENT,name VARCHAR(100) NOT NULL,comment TEXT NOT NULL,PRIMARY KEY(id));
